name: Build Flutter APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. جلب الكود الحالي (lib و pubspec فقط)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. تثبيت جافا
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # 4. توليد مجلد أندرويد رسمي متوافق ومتكامل ومحدث داخل السيرفر
      - name: Generate Fresh Android Project
        run: |
          flutter create --org com.minimalist --platforms android .

      # 5. جلب المكتبات وضبط الإعدادات
      - name: Install dependencies
        run: flutter pub get

      # 6. بناء ملف الـ APK النهائي
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      # 7. رفع التطبيق الجاهز للتحميل
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Detox-App
          path: build/app/outputs/flutter-apk/app-release.apk
